# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  (1..2).each do |i|
    config.vm.define "cassandra#{i}" do |node|
      node.vm.hostname = "cassandra#{i}"
      node.vm.box = "bento/ubuntu-14.04"
      node.vm.network "private_network", ip: "192.168.33.1#{i}"

      # Opsional. Edit sesuai dengan nama network adapter di komputer
      # node.vm.network "public_network", bridge: "Qualcomm Atheros QCA9377 Wireless Network Adapter"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "cassandra#{i}"
        vb.gui = false
        vb.memory = "1024"
      end

      node.vm.provision "shell", path: "provision/bootstrap-cassandra#{i}.sh", privileged: false
    end
  end
end
